language: cpp
sudo: false
dist: xenial

compiler:
- gcc

addons:
  postgresql: "9.5"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake
    - bison
    - clang-5.0
    - cpp-6
    - flex
    - gcc-6
    - g++-6
    - libpq-dev
    - libpq5
    - libstdc++6
    - libtool
    - llvm-5.0
    - pkg-config
    - clang-format-5.0
    - perl
    - parallel

script: ./travis-build.sh

cache:
  directories:
  - $HOME/.ccache

notifications:
  email: true

stages:
  - compile
  - test

matrix:
  fast_finish: true
  include:
    - stage: compile
      compiler: clang
      script: ./travis-build.sh --disable-tests
    - stage: compile
      compiler: gcc
      script: ./travis-build.sh --disable-tests

